# Statistical Mechanics Homework 1
## Name:   陳姿安 bobo &ensp; &ensp; ID: s106022545
## Problem 1: One die with S sides

### 1. What are the theoretical values of the mean, variance, and standard deviation as functions of S? The answers should be in closed form, rather than expressed as a sum.

#### mean: &emsp; $\langle s\rangle = \frac{(s+1)}{2}$ <br>
#### variance: &emsp; $\sigma^2 = \frac{(s-1)(s+1)}{12}$ <br>
#### standard: &emsp; $\sigma = \sqrt{\frac{(s-1)(s+1)}{12}}$

### 2. Modify the program you used for an earlier problem to simulate rolling a die with S sides, and print out the mean, variance, and standard deviation for a number of trials. Have the program print out the theoretical predictions in each case, as well as the deviations from theory to facilitate comparisons.

my code:

In [30]:
import time
import numpy as np

def OneDieS_np(trials, s):
    c1=time.clock()
    print("=================================================================================")
    print("Number of sides = ", s)
    print("Number of trials = ", trials)
    mean_th=(s + 1)/2
    variance_th=(s - 1)*(s + 1)/12
    standard_th=variance_th**0.5
    

    histogram = np.zeros(s)
    print(histogram)

    r = 0
    for t in range(trials):
        r = int(np.random.random()*s)
        histogram[r] = histogram[r] + 1
    print(histogram)
    pro = histogram/trials
    side = [i+1 for i in range(s)]
    mean_ex = np.dot(side,pro)
    sidee = [(i+1)**2 for i in range(s)]
    var = np.dot(sidee,pro)
    vari = (np.dot(side,pro))**2
    variance_ex = var-vari
    standard_ex = variance_ex**0.5
    print('mean:', mean_ex)
    print('variance:',variance_ex)
    print('standard:',standard_ex)
    
    
    print("------------------------------------------------------------------------------")
    
    print("| Mean-th | Mean-ex | Variance-th | Variance-ex | Standard-th | Standard-ex |")
    
    print("|{:^9.3f}|{:^9.3f}|{:^13.3f}|{:^13.3f}|{:^13.3f}|{:^13.3f}|".format(
    mean_th, mean_ex, variance_th, variance_ex, standard_th, standard_ex))
    
    print("------------------------------------------------------------------------------")
    
    print("Mean error : {:2.2f}%".format(100 * abs(mean_th-mean_ex) / mean_th))
    print("Variance error : {:2.2f}%".format(100 * abs(variance_th-variance_ex) / variance_th))
    print("Standard error : {:2.2f}%".format(100 * abs(standard_th-standard_ex) / standard_th))
    

    c2=time.clock()
    print("Elapsed time =", c2-c1)

def bobo():
    OneDieS_np(10000, 8)
    OneDieS_np(1000000, 8)
bobo()
print("\n{:>70}".format("By Bobo"))

Number of sides =  8
Number of trials =  10000
[0. 0. 0. 0. 0. 0. 0. 0.]
[1204. 1249. 1285. 1289. 1242. 1228. 1202. 1301.]
mean: 4.5113
variance: 5.229072309999996
standard: 2.286716490953786
------------------------------------------------------------------------------
| Mean-th | Mean-ex | Variance-th | Variance-ex | Standard-th | Standard-ex |
|  4.500  |  4.511  |    5.250    |    5.229    |    2.291    |    2.287    |
------------------------------------------------------------------------------
Mean error : 0.25%
Variance error : 0.40%
Standard error : 0.20%
Elapsed time = 0.02324456945325437
Number of sides =  8
Number of trials =  1000000
[0. 0. 0. 0. 0. 0. 0. 0.]
[124692. 124774. 125146. 125666. 125191. 124784. 125093. 124654.]
mean: 4.499884
variance: 5.241213986544
standard: 2.2893697793375365
------------------------------------------------------------------------------
| Mean-th | Mean-ex | Variance-th | Variance-ex | Standard-th | Standard-ex |
|  4.500  |  4.500  |    5.

### 3. Run your program for two different values of S. Are the results for the mean, variance, and standard deviation consistent with your predictions?

In [42]:
import time
import numpy as np

def OneDieS_np(trials, s):
    c1=time.clock()
    print("=================================================================================")
    print("Number of sides = ", s)
    print("Number of trials = ", trials)
    mean_th=(s + 1)/2
    variance_th=(s - 1)*(s + 1)/12
    standard_th=variance_th**0.5
    

    histogram = np.zeros(s)
    print(histogram)

    r = 0
    for t in range(trials):
        r = int(np.random.random()*s)
        histogram[r] = histogram[r] + 1
    print(histogram)
    pro = histogram/trials
    side = [i+1 for i in range(s)]
    mean_ex = np.dot(side,pro)
    sidee = [(i+1)**2 for i in range(s)]
    var = np.dot(sidee,pro)
    vari = (np.dot(side,pro))**2
    variance_ex = var-vari
    standard_ex = variance_ex**0.5
    print('mean:', mean_ex)
    print('variance:',variance_ex)
    print('standard:',standard_ex)
    
    
    print("------------------------------------------------------------------------------")
    
    print("| Mean-th | Mean-ex | Variance-th | Variance-ex | Standard-th | Standard-ex |")
    
    print("|{:^9.3f}|{:^9.3f}|{:^13.3f}|{:^13.3f}|{:^13.3f}|{:^13.3f}|".format(
    mean_th, mean_ex, variance_th, variance_ex, standard_th, standard_ex))
    
    print("------------------------------------------------------------------------------")
    
    print("Mean error : {:2.2f}%".format(100 * abs(mean_th-mean_ex) / mean_th))
    print("Variance error : {:2.2f}%".format(100 * abs(variance_th-variance_ex) / variance_th))
    print("Standard error : {:2.2f}%".format(100 * abs(standard_th-standard_ex) / standard_th))
    

    c2=time.clock()
    print("Elapsed time =", c2-c1)

def bobo():
    OneDieS_np(1000000, 10)
    OneDieS_np(1000000, 20)
bobo()
print("\n{:>70}".format("By Bobo"))

Number of sides =  10
Number of trials =  1000000
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 99778. 100625. 100088.  99752. 100056.  99961. 100066.  99569.  99845.
 100260.]
mean: 5.498565
variance: 8.253975940774993
standard: 2.8729733623504052
------------------------------------------------------------------------------
| Mean-th | Mean-ex | Variance-th | Variance-ex | Standard-th | Standard-ex |
|  5.500  |  5.499  |    8.250    |    8.254    |    2.872    |    2.873    |
------------------------------------------------------------------------------
Mean error : 0.03%
Variance error : 0.05%
Standard error : 0.02%
Elapsed time = 2.6868708408856037
Number of sides =  20
Number of trials =  1000000
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[49919. 50148. 50145. 50030. 50158. 50411. 50025. 50214. 49738. 50050.
 50132. 49722. 49911. 49979. 50073. 49820. 49820. 50065. 49988. 49652.]
mean: 10.489857
variance: 33.235277119550986
standard: 5.765004520340898
----------------------

### 4. Experiment with different numbers of trials. How many trials do you need to obtain a rough estimate for the values of the mean and standard deviation? How many trials do you need to obtain an error of less than 1%? Do you need the same number of trials to obtain 1% accuracy for the mean and standard deviation.


In [41]:
import time
import numpy as np

def OneDieS_np(trials, s):
    c1=time.clock()
    print("=================================================================================")
    print("Number of sides = ", s)
    print("Number of trials = ", trials)
    mean_th=(s + 1)/2
    variance_th=(s - 1)*(s + 1)/12
    standard_th=variance_th**0.5
    

    histogram = np.zeros(s)
    print(histogram)

    r = 0
    for t in range(trials):
        r = int(np.random.random()*s)
        histogram[r] = histogram[r] + 1
    print(histogram)
    pro = histogram/trials
    side = [i+1 for i in range(s)]
    mean_ex = np.dot(side,pro)
    sidee = [(i+1)**2 for i in range(s)]
    var = np.dot(sidee,pro)
    vari = (np.dot(side,pro))**2
    variance_ex = var-vari
    standard_ex = variance_ex**0.5
    print('mean:', mean_ex)
    print('variance:',variance_ex)
    print('standard:',standard_ex)
    
    
    print("------------------------------------------------------------------------------")
    
    print("| Mean-th | Mean-ex | Variance-th | Variance-ex | Standard-th | Standard-ex |")
    
    print("|{:^9.3f}|{:^9.3f}|{:^13.3f}|{:^13.3f}|{:^13.3f}|{:^13.3f}|".format(
    mean_th, mean_ex, variance_th, variance_ex, standard_th, standard_ex))
    
    print("------------------------------------------------------------------------------")
    
    print("Mean error : {:2.2f}%".format(100 * abs(mean_th-mean_ex) / mean_th))
    print("Variance error : {:2.2f}%".format(100 * abs(variance_th-variance_ex) / variance_th))
    print("Standard error : {:2.2f}%".format(100 * abs(standard_th-standard_ex) / standard_th))
    

    c2=time.clock()
    print("Elapsed time =", c2-c1)

def bobo():
    OneDieS_np(3000, 20)
bobo()
print("\n{:>70}".format("By Bobo"))

Number of sides =  20
Number of trials =  3000
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[146. 149. 133. 155. 158. 148. 185. 157. 154. 151. 150. 147. 146. 166.
 127. 142. 128. 164. 150. 144.]
mean: 10.419666666666668
variance: 32.66954655555553
standard: 5.715727998737827
------------------------------------------------------------------------------
| Mean-th | Mean-ex | Variance-th | Variance-ex | Standard-th | Standard-ex |
| 10.500  | 10.420  |   33.250    |   32.670    |    5.766    |    5.716    |
------------------------------------------------------------------------------
Mean error : 0.77%
Variance error : 1.75%
Standard error : 0.88%
Elapsed time = 0.017951008906948118

                                                               By Bobo


結果: 

骰20面的骰子3000次可以得到平均值以及標準差的誤差小於1%的結果如上所式。