# Statistical Mechanics Assignment 1
## Name:   陳姿安 bobo &ensp; &ensp; ID: s106022545
## Problem 0:  One die with 6 sides

1.2.code and print-out

In [19]:
import random
import time
import numpy as np

def OneDie_np(trials):
    c1=time.clock()
    print("====================")
    print("One die with 6 sides")
    print("Number of trials = ", trials)

    sides = 6
    histogram = np.zeros(sides)
    print(histogram)

    r = 0
    for j in range(trials):
        r = int(np.random.random()*sides) 
        histogram[r] = histogram[r] + 1

    print("s, N_s, N_s-N/6, N_s/N, N_s/N-1/6")

    for j in range(sides):
        print(j+1, histogram[j], histogram[j]-trials/sides, histogram[j]/trials, histogram[j]/trials-1/6)

    c2=time.clock()
    print("Elapsed time =", c2-c1)

def bobo():
    OneDie_np(1)
    OneDie_np(10)
    OneDie_np(100)
    OneDie_np(1000)
    OneDie_np(10000)
    OneDie_np(100000)
    OneDie_np(300000)

bobo()

print("\n{:>70}".format("By Bobo"))

One die with 6 sides
Number of trials =  1
[0. 0. 0. 0. 0. 0.]
s, N_s, N_s-N/6, N_s/N, N_s/N-1/6
1 0.0 -0.16666666666666666 0.0 -0.16666666666666666
2 0.0 -0.16666666666666666 0.0 -0.16666666666666666
3 1.0 0.8333333333333334 1.0 0.8333333333333334
4 0.0 -0.16666666666666666 0.0 -0.16666666666666666
5 0.0 -0.16666666666666666 0.0 -0.16666666666666666
6 0.0 -0.16666666666666666 0.0 -0.16666666666666666
Elapsed time = 0.0018924307901215798
One die with 6 sides
Number of trials =  10
[0. 0. 0. 0. 0. 0.]
s, N_s, N_s-N/6, N_s/N, N_s/N-1/6
1 2.0 0.33333333333333326 0.2 0.033333333333333354
2 4.0 2.333333333333333 0.4 0.23333333333333336
3 1.0 -0.6666666666666667 0.1 -0.06666666666666665
4 1.0 -0.6666666666666667 0.1 -0.06666666666666665
5 1.0 -0.6666666666666667 0.1 -0.06666666666666665
6 1.0 -0.6666666666666667 0.1 -0.06666666666666665
Elapsed time = 0.0012777756555806263
One die with 6 sides
Number of trials =  100
[0. 0. 0. 0. 0. 0.]
s, N_s, N_s-N/6, N_s/N, N_s/N-1/6
1 11.0 -5.66666666666

3.

Number of trials :  300000 
 
Elapsed time :  1.011091731291799 sec


| sides | N_s   | N_s-N/6 | N_s/N               | N_s/N-1/6              |
|-------|-------|---------|---------------------|------------------------|
|   1   | 50050 |    50   | 0.16683333333333333 | 0.00016666666666667607 |
|   2   | 50311 |   311   | 0.16770333333333334 |  0.0010366666666666857 |
|   3   | 49823 |   -177  | 0.16607666666666668 | -0.0005899999999999794 |
|   4   | 49726 |   -274  | 0.16575333333333334 | -0.0009133333333333216 |
|   5   | 50336 |   336   | 0.16778666666666667 |  0.0011200000000000099 |
|   6   | 49754 |   -246  | 0.16584666666666667 | -0.0008199999999999874 |

4.

Q:  
As the number of trials increases, does the magnitude (absolute value) of the differences between the number of times a given side occurs and one-sixth of the number of trials increase or decrease?

Ans:  
decrease. Because in my code trials more , the  N_s-N/6  會增加，但是相對於總次數而言誤差是減少的。



5.

Q:  
As you increase the number of trials, does the ratio of the number of times each side occurs to the total number of trials approach closer to 1/6?

Ans:  
Yes. When I run 300000 the N_s/N-1/6 mean is  0.0007744444444444434 , very closer to zero.


In [20]:
print("\n{:>70}".format("By Bobo")) #姿安的簽名檔


                                                               By Bobo
